### PR TITLE
Minor typo fix and some doc/read me updates

### PR DESCRIPTION
**Pull request by acrylian**
A few minor things I spotted. I hope you don't mind if I join development a little. I guess we don't need to re-invent the wheel regarding our own api plans.

### CODE REVIEW

**Comment by deanmoses** [comment]
Thanks, will integrate tonight!

**Comment by deanmoses** [comment]
@acrylian, I have a small suite of REST tests for this plugin running on Postman (https://www.getpostman.com/).  Happy to share them (Postman has facilities for sharing tests). 
 However, they hit my personal  gallery, which I'm not going to create a bunch of test data on.  Do you guys have a set of test galleries somewhere that I can install this plugin on and hit, or some way I can add test cases (and test data) to a continuous integration process?

**Comment by acrylian** [comment]
Besides our own site and the demo there are no public test sites we can offer access to. We primarily develop using local servers. As a Mac user I use MAMP, but there are similar like WAMP for Windows or LAMP for Linux. Those match the "standard (shared) webhost" Zenphoto primarily aims at quite well. Maybe that would be something for you as well instead of hitting your actual webspace?

I have some ideas/suggestions for this plugin as I had a list of things already I thought an api might need to cover. For example Zenpage plugin news articles, categories and pages need to be covered in any case if we maybe consider to even make this the official api plugin later. I am willing to help as much as I can.

I might open some suggestion tickets based on my list later on if that's okay for you.

**Comment by deanmoses** [comment]
Yes, please share your list via tickets.  I'm doing this because I've gotten a ton of value out of Zenphoto over the years and want to give back.  You want me to make you a contributor so you can commit directly?

Can I set up multiple zenphoto installations, each in their own directory?  This'd be on Linux.

**Comment by acrylian** [comment]
Thanks, glad to hear Zenphoto is that useful to you and that you wish to contribute back! That is very welcome. 

Thanks for the offer of becoming a contributor. That probably would be useful. I will open tickets soon once I sorted the list a bit. 

> Can I set up multiple zenphoto installations, each in their own directory? This'd be on Linux.

Of course!

**Comment by acrylian** [comment]
Just to note, since I collaborate here and there is the option to make this official later, there is actually no need to open tickets on our side. It's primarily just me anyway. Maybe you could also mail me via malte[at]zenphoto.org so we may communicate more directly in case it is needed.

Promised tickets with suggestions/ideas coming soon.

**Pull request merged**
